name: "UpdateDependenciesUpdateLibrary"
author: "Siarhei Dudko <admin@sergdudko.tk>"
description: "Automatic update of package dependencies with version up"
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  author-email:
    description: "Author's email of the commit."
    default: "actions@github.com"
  author-name:
    description: "Author's name of the commit."
    default: "GitHUB Actions"
  ref:
    description: "Repository name with owner. For example, siarheidudko/autoupdater."
    default: ${{ github.repository }}
  branch:
    description: "Name of the branch."
    default: "master"
  working-directory:
    description: "Working directory."
    default: ${{ github.workspace }}
  changelog-file:
    description: "Path to changelog file."
    default: "./CHANGELOG.md"
  package-file:
    description: "Path to package.json file."
    default: "./package.json"
  package-manager:
    description: "Package manager (npm or yarn)."
    default: "npm"
  debug:
    description: "Show debugging log."
    default: "false"
  builds-and-checks:
    description: "Checks to be performed before the push."
  ignore-packages:
    description: "Package names that should not be updated."
outputs:
  updated:
    description: "Update flag. If true, then the version has been updated."
  dir:
    description: "Directory with updates."
  version:
    description: "Package version."
runs:
  using: "node16"
  main: "main.js"
  post: "cleanup.js"
branding:
  icon: "arrow-right-circle"
  color: "green"
